export default [
  { "id": "A101", "title": "Propulsion Assignment", "course": "RS101" },
  { "id": "A102", "title": "Combustion Analysis", "course": "RS101" },
  { "id": "A103", "title": "Nozzle Design Project", "course": "RS101" },
  { "id": "A201", "title": "Aerodynamics Quiz", "course": "RS102" },
  { "id": "A202", "title": "Flow Analysis", "course": "RS102" },
  { "id": "A203", "title": "Heating Analysis", "course": "RS102" },
  { "id": "A301", "title": "Structural Design Task", "course": "RS103" },
  { "id": "A302", "title": "Orbital Calculations", "course": "RS103" },
  { "id": "A303", "title": "Systems Engineering Exam", "course": "RS103" },
  { "id": "A401", "title": "Algorithms PS 1", "course": "CS123" },
  { "id": "A402", "title": "Algorithms Quiz 1", "course": "CS123" },
  { "id": "A403", "title": "Algorithms Project", "course": "CS123" },
  { "id": "A501", "title": "Assignment 1", "course": "CS456" },
  { "id": "A502", "title": "Find Project Partners", "course": "CS456" },
  { "id": "A503", "title": "Start Midterm Project", "course": "CS456" },
  { "id": "A601", "title": "Data Visualization Practice", "course": "DS100" },
  { "id": "A602", "title": "Python Practice", "course": "DS100" },
  { "id": "A603", "title": "Quiz 1", "course": "DS100" },
  { "id": "A701", "title": "Prep Work", "course": "IS300" },
  { "id": "A702", "title": "Heuristics Activity", "course": "IS300" },
  { "id": "A703", "title": "Choose a Website", "course": "IS300" }
]
